version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: prisma_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prisma-setup:
    build: ./service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/mydb?schema=public"
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npx ts-node prisma/seed.ts
      "
    restart: "no"

  backend:
    build: ./service
    container_name: prisma_backend
    depends_on:
      prisma-setup:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/mydb?schema=public"
    ports:
      - "3000:3000"
    working_dir: /service
    restart: unless-stopped
    command: npm run dev

volumes:
  pgdata:
